OBJS = \
	$(O)/main.c.o \
	$(O)/data/cpuid-arm.c.o \
	$(O)/data/efi_guids.c.o \
	$(O)/data/gpu-db.c.o \
	$(O)/data/string.c.o \
	$(O)/logo/ami.c.o \
	$(O)/logo/apple.c.o \
	$(O)/logo/dell.c.o \
	$(O)/logo/hp.c.o \
	$(O)/logo/huawei.c.o \
	$(O)/logo/insyde.c.o \
	$(O)/logo/lenovo.c.o \
	$(O)/logo/microsoft.c.o \
	$(O)/logo/parsec.c.o \
	$(O)/logo/phoenix.c.o \
	$(O)/logo/qcom.c.o \
	$(O)/logo/quanta.c.o \
	$(O)/logo/virtualbox.c.o \
	$(O)/logo/vmware.c.o \
	$(O)/logo/uboot.c.o \
	$(O)/logo/uefi.c.o \
	$(O)/logo/tianocore.c.o \
	$(O)/logo/logo.c.o \
	$(O)/logo/logos.c.o \
	$(O)/lib/alloc.c.o \
	$(O)/lib/ctype.c.o \
	$(O)/lib/dbg.c.o \
	$(O)/lib/dump.c.o \
	$(O)/lib/encode.c.o \
	$(O)/lib/init.c.o \
	$(O)/lib/mem.c.o \
	$(O)/lib/net.c.o \
	$(O)/lib/num.c.o \
	$(O)/lib/print.c.o \
	$(O)/lib/printf.c.o \
	$(O)/lib/readable.c.o \
	$(O)/lib/regexp.c.o \
	$(O)/lib/stb_sprintf.c.o \
	$(O)/lib/stderr.c.o \
	$(O)/lib/stdout.c.o \
	$(O)/lib/str.c.o \
	$(O)/lib/utils.c.o \
	$(O)/info/info.c.o \
	$(O)/info/gpu.c.o \
	$(O)/info/fdt.c.o \
	$(O)/info/fs.c.o \
	$(O)/info/cpuid.c.o \
	$(O)/info/disk.c.o \
	$(O)/info/mem.c.o \
	$(O)/info/net.c.o \
	$(O)/info/time.c.o \
	$(O)/info/smbios.c.o \
	$(O)/info/smbios_base.c.o \
	$(O)/info/sys.c.o \
	$(O)/libfdt/fdt.c.o \
	$(O)/libfdt/fdt_addresses.c.o \
	$(O)/libfdt/fdt_check.c.o \
	$(O)/libfdt/fdt_empty_tree.c.o \
	$(O)/libfdt/fdt_overlay.c.o \
	$(O)/libfdt/fdt_ro.c.o \
	$(O)/libfdt/fdt_rw.c.o \
	$(O)/libfdt/fdt_strerror.c.o \
	$(O)/libfdt/fdt_sw.c.o \
	$(O)/libfdt/fdt_wip.c.o \
	$(O)/entry/relocate-$(ARCH).c.o \
	$(O)/entry/start-$(ARCH).S.o \
	$(O)/entry/relocate.S.o
